const GLOBOS = [
  {
    name: 'tuky',
    price: Math.floor(Math.random() * 100),
    catalogId: 1,
    color: 'perlado',
    cant: 50,
    size: '',
    img: 'http://res.cloudinary.com/circus-corillon/image/upload/v1664505400/products/sza86x79iuvwk37fuft0.png',
  },
  {
    name: 'tuky',
    price: 1,
    catalogId: 1,
    color: 'std',
    cant: 50,
    size: '',
    img: 'http://res.cloudinary.com/circus-corillon/image/upload/v1664505400/products/kfxfbxyn5pbldyxoxo6y.png',
  },
  {
    name: 'party time',
    price: Math.floor(Math.random() * 100),
    catalogId: 1,
    color: 'std',
    cant: 50,
    size: '',
    img: 'http://res.cloudinary.com/circus-corillon/image/upload/v1664505400/products/u23wsojkbmts3rhe9ttx.png',
  },
  {
    name: 'globox',
    price: Math.floor(Math.random() * 100),
    catalogId: 1,
    color: 'perlado',
    cant: 50,
    size: '',
    img: 'http://res.cloudinary.com/circus-corillon/image/upload/v1664505400/products/hgci3yiii2knrkmgdnbd.png',
  },
  {
    name: 'party time',
    price: Math.floor(Math.random() * 100),
    catalogId: 1,
    color: 'perlado',
    cant: 25,
    size: '',
    img: 'http://res.cloudinary.com/circus-corillon/image/upload/v1664505400/products/aeiqswwqohgmwdwfwfe6.png',
  },
];

const GLOBOS_NUMEROS = [
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
    img: 'http://res.cloudinary.com/circus-corillon/image/upload/v1664505400/products/byrdwcbjsxtcj8wuyq0n.png',
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rosa',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'negro',
    cant: 0,
    size: `16"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'oro',
    cant: 0,
    size: `32"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'plata',
    cant: 0,
    size: `40"`,
  },
  {
    name: 'cero',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'uno',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'dos',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'tres',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'cuatro',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'cinco',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'seis',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'siete',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'ocho',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'nueve',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
  {
    name: 'diez',
    price: Math.floor(Math.random() * 100),
    catalogId: 2,
    color: 'rojo',
    cant: 0,
    size: `34"`,
  },
];

const CORTINAS_METALIZADAS = [
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'oro',
    cant: 0,
    size: ``,
  },
  {
    name: 'rojo',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rosa gold',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'pastel',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'multicolor',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'negro',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'fucsia',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'verde',
    cant: 0,
    size: ``,
  },
  {
    name: 'lluvia',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'blanco',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rojo',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'oro',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'azul',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rosa gold',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'oro',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rojo',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'azul',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'negro',
    cant: 0,
    size: ``,
  },
  {
    name: 'estrella',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'fucsia',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'oro',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'violeta',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'fucsia',
    cant: 0,
    size: ``,
  },
  {
    name: 'square',
    price: Math.floor(Math.random() * 100),
    catalogId: 3,
    color: 'verde',
    cant: 0,
    size: ``,
  },
];

const BANDERINES_FC = [
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'oro',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'negro',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'rojo',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'azul',
    cant: 0,
    size: ``,
  },
  {
    name: 'liso',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'pastel',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'dorado',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'negro',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'fucsia',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'azul',
    cant: 0,
    size: ``,
  },
  {
    name: 'gibreado',
    price: Math.floor(Math.random() * 100),
    catalogId: 4,
    color: 'rojo',
    cant: 0,
    size: ``,
  },
];

const RADHA = [
  {
    name: 'polvos',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'verde',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'verde aqua',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'amarillo',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'naranja',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'violeta',
    cant: 0,
    size: ``,
  },
  {
    name: 'splash',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'splash',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'verde',
    cant: 0,
    size: ``,
  },
  {
    name: 'splash',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'amarillo',
    cant: 0,
    size: ``,
  },
  {
    name: 'splash',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'rosa',
    cant: 0,
    size: ``,
  },
  {
    name: 'splash',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'violeta',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos fluo',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'naranja',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos fluo',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'amarillo',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos fluo',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'verde',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos fluo',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'celeste',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos fluo',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'fucsia',
    cant: 0,
    size: ``,
  },
  {
    name: 'polvos fluo',
    price: Math.floor(Math.random() * 100),
    catalogId: 5,
    color: 'violeta',
    cant: 0,
    size: ``,
  },
];

const LANZA_PAPELES = [
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 6,
    color: 'rosa gold',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 6,
    color: 'plata',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 6,
    color: 'oro',
    cant: 0,
    size: ``,
  },
  {
    name: 'corazon',
    price: Math.floor(Math.random() * 100),
    catalogId: 6,
    color: 'multicolor',
    cant: 0,
    size: ``,
  },
];

const SET_DE_GLOBOS = [
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rosa gold',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'dorado',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'plata',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'dorado negro',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rosa',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'violeta',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rojo',
    cant: 9,
    size: ``,
  },
  {
    name: 'set9',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'azul',
    cant: 9,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'dorado',
    cant: 10,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rosa gold',
    cant: 10,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'plata',
    cant: 10,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rosa',
    cant: 10,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rojo',
    cant: 10,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'azul',
    cant: 10,
    size: ``,
  },
  {
    name: 'set10',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'negro',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'dorado',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rosa gold',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'dorado negro',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rosa',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'violeta',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'rojo',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'verde',
    cant: 10,
    size: ``,
  },
  {
    name: 'set14',
    price: Math.floor(Math.random() * 100),
    catalogId: 7,
    color: 'negro',
    cant: 10,
    size: ``,
  },
];

const BURBUJA_CON_CONFETTI = [
  {
    name: 'chico',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'rojo',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'chico',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'fucsia',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'chico',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'azul',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'chico',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'plata',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'chico',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'dorado',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'grande',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'multicolor',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'grande',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'azul',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'grande',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'rojo',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'grande',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'rosa gold',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'grande',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'fucsia',
    cant: 10,
    size: `18"`,
  },
  {
    name: 'extra grande',
    price: Math.floor(Math.random() * 100),
    catalogId: 8,
    color: 'multicolor',
    cant: 10,
    size: `24"`,
  },
];

const catalogos = [
  {
    id: 1,
    name: 'globos',
  },
  {
    id: 2,
    name: 'globos_numeros',
  },
  {
    id: 3,
    name: 'cortinas_metalizadas',
  },
  {
    id: 4,
    name: 'banderines_fc',
  },
  {
    id: 5,
    name: 'radha',
  },
  {
    id: 6,
    name: 'lanza_papeles',
  },
  {
    id: 7,
    name: 'set_de_globos',
  },
  {
    id: 8,
    name: 'burbuja_con_confetti',
  },
];

const inventario = [
  ...GLOBOS,
  ...GLOBOS_NUMEROS,
  ...CORTINAS_METALIZADAS,
  ...BANDERINES_FC,
  ...RADHA,
  ...LANZA_PAPELES,
  ...SET_DE_GLOBOS,
  ...BURBUJA_CON_CONFETTI,
];

module.exports = {
  inventario,
  catalogos,
};
