const GLOBOS = [{
    nombre:"tuky",
    precio:0,
    imagen:"",
    color:"perlado",
    cantidad:50,
    tamanio:""
},{
    nombre:"tuky",
    precio:0,
    imagen:"",
    color:"std",
    cantidad:50,
    tamanio:""
},{
    nombre:"party time",
    precio:0,
    imagen:"",
    color:"std",
    cantidad:50,
    tamanio:""
},{
    nombre:"globox",
    precio:0,
    imagen:"",
    color:"perlado",
    cantidad:50,
    tamanio:""
},{
    nombre:"party time",
    precio:0,
    imagen:"",
    color:"perlado",
    cantidad:25,
    tamanio:""
}]

const GLOBOS_NUMEROS = [{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"rosa",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"negro",
    cantidad:0,
    tamanio:`16"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"oro",
    cantidad:0,
    tamanio:`32"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"plata",
    cantidad:0,
    tamanio:`40"`
},{
    nombre:"cero",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"uno",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"dos",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"tres",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"cuatro",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"cinco",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"seis",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"siete",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"ocho",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"nueve",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},{
    nombre:"diez",
    precio:0,
    imagen:"",
    color:"rojo",
    cantidad:0,
    tamanio:`34"`
},]

const CORTINAS_METALIZADAS = [
    {
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"oro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"rojo",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"pastel",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"multicolor",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"negro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"verde",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lluvia",
        precio:0,
        imagen:"",
        color:"blanco",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"oro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"oro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"negro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"estrella",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"oro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"violeta",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:0,
        tamanio:``
    },{
        nombre:"square",
        precio:0,
        imagen:"",
        color:"verde",
        cantidad:0,
        tamanio:``
    },
]

const BANDERINES_FC = [
    {
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"oro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"negro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:0,
        tamanio:``
    },{
        nombre:"lisos",
        precio:0,
        imagen:"",
        color:"pastel",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"dorado",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"negro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:0,
        tamanio:``
    },{
        nombre:"gibreado",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:0,
        tamanio:``
    },
]

const RADHA = [
    {
        nombre:"polvos",
        precio:0,
        imagen:"",
        color:"verde",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos",
        precio:0,
        imagen:"",
        color:"verde aqua",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos",
        precio:0,
        imagen:"",
        color:"amarillo",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos",
        precio:0,
        imagen:"",
        color:"naranja",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos",
        precio:0,
        imagen:"",
        color:"violeta",
        cantidad:0,
        tamanio:``
    },{
        nombre:"splash",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"splash",
        precio:0,
        imagen:"",
        color:"verde",
        cantidad:0,
        tamanio:``
    },{
        nombre:"splash",
        precio:0,
        imagen:"",
        color:"amarillo",
        cantidad:0,
        tamanio:``
    },{
        nombre:"splash",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:0,
        tamanio:``
    },{
        nombre:"splash",
        precio:0,
        imagen:"",
        color:"violeta",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos fluo",
        precio:0,
        imagen:"",
        color:"naranja",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos fluo",
        precio:0,
        imagen:"",
        color:"amarillo",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos fluo",
        precio:0,
        imagen:"",
        color:"verde",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos fluo",
        precio:0,
        imagen:"",
        color:"celeste",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos fluo",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:0,
        tamanio:``
    },{
        nombre:"polvos fluo",
        precio:0,
        imagen:"",
        color:"violeta",
        cantidad:0,
        tamanio:``
    },
]

const LANZA_PAPELES = [
    {
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"oro",
        cantidad:0,
        tamanio:``
    },{
        nombre:"corazon",
        precio:0,
        imagen:"",
        color:"multicolor",
        cantidad:0,
        tamanio:``
    },
]

const SET_DE_GLOBOS = [
    {
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"dorado",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"dorado/negro",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"violeta",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set9",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:9,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"dorado",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set10",
        precio:0,
        imagen:"",
        color:"negro",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"dorado",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"dorado/negro",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"rosa",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"violeta",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"verde",
        cantidad:10,
        tamanio:``
    },{
        nombre:"set14",
        precio:0,
        imagen:"",
        color:"negro",
        cantidad:10,
        tamanio:``
    },
]

const BURBUJA_CON_CONFETTI = [
    {
        nombre:"chico",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"chico",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"chico",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"chico",
        precio:0,
        imagen:"",
        color:"plata",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"chico",
        precio:0,
        imagen:"",
        color:"dorado",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"grande",
        precio:0,
        imagen:"",
        color:"multicolor",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"grande",
        precio:0,
        imagen:"",
        color:"azul",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"grande",
        precio:0,
        imagen:"",
        color:"rojo",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"grande",
        precio:0,
        imagen:"",
        color:"rosa gold",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"grande",
        precio:0,
        imagen:"",
        color:"fucsia",
        cantidad:10,
        tamanio:`18"`
    },{
        nombre:"extra grande",
        precio:0,
        imagen:"",
        color:"multicolor",
        cantidad:10,
        tamanio:`24"`
    },
]

const productos = {GLOBOS,GLOBOS_NUMEROS,CORTINAS_METALIZADAS,BANDERINES_FC,RADHA,LANZA_PAPELES,SET_DE_GLOBOS,BURBUJA_CON_CONFETTI}



module.exports=productos